// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.PaymentProcessor.TokenLedger.Infrastructure;

#nullable disable

namespace PaymentProcessor.TokenLedger.Infrastructure.Migrations
{
    [DbContext(typeof(TokenDbContext))]
    [Migration("20260713202035_InitialTokenLedger")]
    partial class InitialTokenLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.PaymentProcessor.TokenLedger.Model.TokenAwardLookupEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TableVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubCategory", "ConditionGrade", "TableVersion")
                        .IsUnique();

                    b.ToTable("TokenAwardLookupEntries");
                });

            modelBuilder.Entity("eShop.PaymentProcessor.TokenLedger.Model.TokenAwardedListing", b =>
                {
                    b.Property<string>("CatalogItemId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AwardedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("CatalogItemId");

                    b.ToTable("TokenAwardedListings");
                });

            modelBuilder.Entity("eShop.PaymentProcessor.TokenLedger.Model.TokenTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("CatalogItemId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LookupTableVersion")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RelatedEventId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("eShop.PaymentProcessor.TokenLedger.Model.TokenWallet", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("TokenWallets");
                });
#pragma warning restore 612, 618
        }
    }
}
